### PR TITLE
Binary Search Code Added

### PR DESCRIPTION
**Pull request by codegoggins**

### CODE REVIEW

**Review by awesometushar000 — APPROVED** [review]
Write time and space complexity in comments

**Comment by codegoggins** [comment]
> Write time and space complexity in comments

Okay Will do

**Comment by codegoggins** [comment]
Have made the necessary changes by adding Space and Time complexity.

**Comment by awesometushar000** [comment]
> Have made the necessary changes by adding Space and Time complexity.

Successful Hack !!!

**Pull request merged**
